name: Terraform Deploy

on:
  push:
    paths:
      - 'infra/**' 
    branches:
      - main
  workflow_dispatch: 

jobs:
  terraform:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout Repository
      uses: actions/checkout@v3

    - name: Setup Terraform
      uses: hashicorp/setup-terraform@v2

    - name: Terraform Init
      run: terraform init
      working-directory: infra  

    - name: Terraform Plan
      run: terraform plan
      working-directory: infra  

    - name: Terraform Apply
      run: terraform apply -auto-approve
      working-directory: infra  
      env:
        AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
        AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
